"""add progress_percent to stem_jobs

Revision ID: 4f1eef4d5ce1
Revises: 8261f42455b9
Create Date: 2026-07-15 16:56:42.956869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f1eef4d5ce1'
down_revision: Union[str, None] = '8261f42455b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'stem_jobs',
        sa.Column('progress_percent', sa.Integer(), nullable=False, server_default='0'),
    )
    op.alter_column('stem_jobs', 'progress_percent', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stem_jobs', 'progress_percent')
    # ### end Alembic commands ###
