"""add song metadata, track metadata and import jobs

Revision ID: 741e1ddbb663
Revises: e6eed7da7ad6
Create Date: 2026-07-13 15:11:43.868974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '741e1ddbb663'
down_revision: Union[str, None] = 'e6eed7da7ad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_jobs',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('zip_storage_path', sa.String(length=500), nullable=False),
    sa.Column('total_files', sa.Integer(), nullable=False),
    sa.Column('processed_files', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_jobs_owner_id'), 'import_jobs', ['owner_id'], unique=False)
    op.create_index(op.f('ix_import_jobs_song_id'), 'import_jobs', ['song_id'], unique=False)
    op.add_column('songs', sa.Column('time_signature', sa.String(length=10), nullable=False, server_default='4/4'))
    op.add_column('songs', sa.Column('language', sa.String(length=50), nullable=True))
    op.add_column('songs', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('songs', sa.Column('tags', sa.String(length=500), nullable=True))
    op.add_column('songs', sa.Column('song_date', sa.Date(), nullable=True))
    op.add_column('songs', sa.Column('cover_image_url', sa.String(length=500), nullable=True))
    op.add_column('songs', sa.Column('color', sa.String(length=20), nullable=False, server_default='#ff8a1f'))
    op.add_column('songs', sa.Column('is_favorite', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('tracks', sa.Column('track_type', sa.String(length=30), nullable=False, server_default='other'))
    op.add_column('tracks', sa.Column('is_hidden', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('tracks', sa.Column('duration_seconds', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'duration_seconds')
    op.drop_column('tracks', 'is_hidden')
    op.drop_column('tracks', 'track_type')
    op.drop_column('songs', 'is_favorite')
    op.drop_column('songs', 'color')
    op.drop_column('songs', 'cover_image_url')
    op.drop_column('songs', 'song_date')
    op.drop_column('songs', 'tags')
    op.drop_column('songs', 'notes')
    op.drop_column('songs', 'language')
    op.drop_column('songs', 'time_signature')
    op.drop_index(op.f('ix_import_jobs_song_id'), table_name='import_jobs')
    op.drop_index(op.f('ix_import_jobs_owner_id'), table_name='import_jobs')
    op.drop_table('import_jobs')
    # ### end Alembic commands ###
