"""add track pan color phase invert

Revision ID: e6eed7da7ad6
Revises: 319e7a6af9ac
Create Date: 2026-07-12 03:31:41.201650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6eed7da7ad6'
down_revision: Union[str, None] = '319e7a6af9ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('pan', sa.Float(), nullable=False, server_default='0'))
    op.add_column('tracks', sa.Column('is_phase_inverted', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('tracks', sa.Column('color', sa.String(length=20), nullable=False, server_default='#ff8a1f'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'color')
    op.drop_column('tracks', 'is_phase_inverted')
    op.drop_column('tracks', 'pan')
    # ### end Alembic commands ###
