"""add end_time_seconds and section sequence items

Revision ID: e71ab7ae94f4
Revises: 4f1eef4d5ce1
Create Date: 2026-07-20 15:22:38.742772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e71ab7ae94f4'
down_revision: Union[str, None] = '4f1eef4d5ce1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section_sequence_items',
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('marker_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['marker_id'], ['song_markers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_section_sequence_items_marker_id'), 'section_sequence_items', ['marker_id'], unique=False)
    op.create_index(op.f('ix_section_sequence_items_song_id'), 'section_sequence_items', ['song_id'], unique=False)
    op.add_column('song_markers', sa.Column('end_time_seconds', sa.Float(), nullable=True))
    # ### end Alembic commands ###

    # Backfill: for every existing marker, end_time_seconds = the next marker's
    # position_seconds within the same song (chronologically), else the song's
    # known duration, else left NULL (open-ended, matches prior implicit behavior).
    op.execute(
        """
        UPDATE song_markers sm
        SET end_time_seconds = COALESCE(
            (
                SELECT MIN(sm2.position_seconds)
                FROM song_markers sm2
                WHERE sm2.song_id = sm.song_id AND sm2.position_seconds > sm.position_seconds
            ),
            (SELECT s.duration_seconds FROM songs s WHERE s.id = sm.song_id)
        )
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song_markers', 'end_time_seconds')
    op.drop_index(op.f('ix_section_sequence_items_song_id'), table_name='section_sequence_items')
    op.drop_index(op.f('ix_section_sequence_items_marker_id'), table_name='section_sequence_items')
    op.drop_table('section_sequence_items')
    # ### end Alembic commands ###
