import {
  AudioLines,
  Disc3,
  Drum,
  Guitar,
  Mic2,
  Music2,
  Piano,
  Radio,
  Repeat,
  Sparkles,
  Users,
  Waves,
  type LucideIcon,
} from "lucide-react";
import type { TrackType } from "@/hooks/use-tracks";

export const TRACK_TYPE_LABELS: Record<TrackType, string> = {
  drums: "Batería",
  kick: "Bombo",
  snare: "Caja",
  hihat: "Hi-Hat",
  percussion: "Percusión",
  bass: "Bajo",
  guitar_electric: "Guitarra Eléctrica",
  guitar_acoustic: "Guitarra Acústica",
  piano: "Piano",
  pad: "Pad",
  strings: "Cuerdas",
  brass: "Metales",
  fx: "FX",
  loops: "Loops",
  click: "Click",
  guide: "Guía",
  lead_vocal: "Voz Principal",
  backing_vocal: "Coros",
  choir: "Choir",
  narration: "Narración",
  midi: "MIDI",
  other: "Otro",
};

export const TRACK_TYPE_ICONS: Record<TrackType, LucideIcon> = {
  drums: Drum,
  kick: Drum,
  snare: Drum,
  hihat: Disc3,
  percussion: Disc3,
  bass: Guitar,
  guitar_electric: Guitar,
  guitar_acoustic: Guitar,
  piano: Piano,
  pad: Waves,
  strings: Music2,
  brass: Music2,
  fx: Sparkles,
  loops: Repeat,
  click: Radio,
  guide: Radio,
  lead_vocal: Mic2,
  backing_vocal: Users,
  choir: Users,
  narration: Mic2,
  midi: AudioLines,
  other: Music2,
};
